plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/mert/hermes_article_pipeline/publishing_hub"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]